pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests -Denforcer.skip=true -Dstyle.color=never clean package'
            }
        }
        stage('Hello GIT') {
            steps {
                echo 'Hello from git'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Denforcer.skip=true -Dstyle.color=never'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
